In [158]:
import pandas as pd
import warnings

In [ ]:
warnings.filterwarnings("ignore")  # to ignore warnings

In [160]:
# Load the dataset
data = pd.read_csv("udemy_courses.csv")
data.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance

In [161]:
data.shape

(3678, 12)

In [162]:
data.isnull().sum() #to check for null values

course_id              0
course_title           0
url                    0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

In [163]:
data.duplicated().sum() #to check for duplicate values

np.int64(6)

In [164]:
data[data.duplicated()]  #to view the duplicate values

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
787,837322,Essentials of money value: Get a financial Life !,https://www.udemy.com/essentials-of-money-value/,True,20,0,0,20,All Levels,0.616667,2016-05-16T18:28:30Z,Business Finance
788,1157298,Introduction to Forex Trading Business For Beg...,https://www.udemy.com/introduction-to-forex-tr...,True,20,0,0,27,Beginner Level,1.500000,2017-04-23T16:19:01Z,Business Finance
894,1035638,Understanding Financial Statements,https://www.udemy.com/understanding-financial-...,True,25,0,0,10,All Levels,1.000000,2016-12-15T14:56:17Z,Business Finance
1100,1084454,CFA Level 2- Quantitative Methods,https://www.udemy.com/cfa-level-2-quantitative...,True,40,0,0,35,All Levels,5.500000,2017-07-02T14:29:35Z,Business Finance
1473,185526,MicroStation - Células,https://www.udemy.com/microstation-celulas/,True,20,0,0,9,Beginner Level,0.616667,2014-04-15T21:48:55Z,Graphic Design
2561,28295,Learn Web Designing & HTML5/CSS3 Essentials in...,https://www.udemy.com/build-beautiful-html5-we...,True,75,43285,525,24,All Levels,4.000000,2013-01-03T00:55:31Z,Web Development

In [165]:
data = data.drop_duplicates()
data.shape  #to drop the duplicate values

(3672, 12)

In [166]:
data.columns  #to view the columns in the dataset

Index(['course_id', 'course_title', 'url', 'is_paid', 'price',
       'num_subscribers', 'num_reviews', 'num_lectures', 'level',
       'content_duration', 'published_timestamp', 'subject'],
      dtype='object')

In [167]:
def pop_rem(data):
    data['pop_score'] = 0.6* data['num_subscribers'] + 0.4 * data['num_reviews']
    # sort the dataset by pop_score
    df_sorted = data.sort_values(by='pop_score', ascending=False)[[ 'course_title', 'pop_score']].head(5)
    return df_sorted

In [168]:
pop_rem(data)   #to get the top 10 courses based on popularity score

                                           course_title  pop_score
2827               Learn HTML5 Programming From Scratch   164805.4
3032                     Coding for Entrepreneurs Basic    96729.0
3230                         The Web Developer Bootcamp    83928.4
3232              The Complete Web Developer Course 2.0    77672.0
2783  Build Your First Website in 1 Week with HTML5 ...    74544.2

In [169]:
import neattext.functions as nfx

In [170]:
#  remove stopwords form column 'course_title'
data['course_title'] = data['course_title'].apply(nfx.remove_stopwords) 
# remove special characters from column 'course_title'
data['course_title'] = data['course_title'].apply(nfx.remove_special_characters)
data['course_title'].head()  #to view the first few rows of the column after removing stopwords

0                   Ultimate Investment Banking Course
1    Complete GST Course  Certification  Grow Practice
2     Financial Modeling Business Analysts Consultants
3          Beginner Pro  Financial Analysis Excel 2017
4                     Maximize Profits Trading Options
Name: course_title, dtype: object

In [ ]:
data['title_subject'] = data['course_title'] + '' + data['subject'] #to create a new column by concatenating 'course_title' and 'subject'
data.head(1)  # to view the first few rows of the dataset

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,pop_score,title_subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance,1297.4,Ultimate Investment Banking CourseBusiness Fin...

In [ ]:

from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer(max_features=3000, stop_words='english')  #to create a count vectorizer object with a maximum of 3000 features
vectors = cv.fit_transform(data['title_subject']).toarray()  # to transform the text data into a matrix of token counts
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [173]:
feature_names = cv.get_feature_names_out()
print( len(feature_names) )  #to get the number of features

3000

In [ ]:
# calculate the cosine similarity between the vectors 
from sklearn.metrics.pairwise import cosine_similarity 
similarity = cosine_similarity(vectors)  #to calculate the cosine similarity between the vectors
similarity

array([[1.        , 0.16903085, 0.2236068 , ..., 0.        , 0.        ,
        0.        ],
       [0.16903085, 1.        , 0.18898224, ..., 0.        , 0.        ,
        0.        ],
       [0.2236068 , 0.18898224, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.21821789,
        0.43643578],
       [0.        , 0.        , 0.        , ..., 0.21821789, 1.        ,
        0.14285714],
       [0.        , 0.        , 0.        , ..., 0.43643578, 0.14285714,
        1.        ]])

In [175]:
similarity.shape  #to get the shape of the similarity matrix

(3672, 3672)

In [176]:
similarity[0]  #to get the similarity scores for the first course

array([1.        , 0.16903085, 0.2236068 , ..., 0.        , 0.        ,
       0.        ])

In [177]:
sorted(enumerate(similarity[0]), reverse=True, key=lambda x: x[1])  # to sort the similarity scores in descending order

[(0, np.float64(0.9999999999999999)),
 (417, np.float64(0.7745966692414834)),
 (39, np.float64(0.5477225575051662)),
 (657, np.float64(0.5477225575051662)),
 (1066, np.float64(0.5477225575051662)),
 (227, np.float64(0.50709255283711)),
 (945, np.float64(0.50709255283711)),
 (41, np.float64(0.47434164902525683)),
 (137, np.float64(0.47434164902525683)),
 (528, np.float64(0.47434164902525683)),
 (722, np.float64(0.47434164902525683)),
 (240, np.float64(0.4472135954999579)),
 (285, np.float64(0.4472135954999579)),
 (418, np.float64(0.4472135954999579)),
 (450, np.float64(0.4472135954999579)),
 (503, np.float64(0.4472135954999579)),
 (942, np.float64(0.4472135954999579)),
 (849, np.float64(0.44721359549995787)),
 (1183, np.float64(0.40451991747794525)),
 (9, np.float64(0.39999999999999997)),
 (120, np.float64(0.39999999999999997)),
 (162, np.float64(0.39999999999999997)),
 (297, np.float64(0.39999999999999997)),
 (354, np.float64(0.39999999999999997)),
 (369, np.float64(0.39999999999999997)),
 (726, np.float64(0.39999999999999997)),
 (736, np.float64(0.39999999999999997)),
 (801, np.float64(0.39999999999999997)),
 (852, np.float64(0.39999999999999997)),
 (861, np.float64(0.39999999999999997)),
 (887, np.float64(0.39999999999999997)),
 (994, np.float64(0.39999999999999997)),
 (1166, np.float64(0.39999999999999997)),
 (76, np.float64(0.3872983346207417)),
 (594, np.float64(0.3872983346207417)),
 (164, np.float64(0.36514837167011077)),
 (262, np.float64(0.36514837167011077)),
 (343, np.float64(0.36514837167011077)),
 (411, np.float64(0.36514837167011077)),
 (522, np.float64(0.36514837167011077)),
 (554, np.float64(0.36514837167011077)),
 (764, np.float64(0.36514837167011077)),
 (802, np.float64(0.36514837167011077)),
 (837, np.float64(0.36514837167011077)),
 (960, np.float64(0.36514837167011077)),
 (1076, np.float64(0.36514837167011077)),
 (1120, np.float64(0.36514837167011077)),
 (1144, np.float64(0.36514837167011077)),
 (128, np.float64(0.3380617018914066)),
 (249, np.float64(0.3380617018914066)),
 (349, np.float64(0.3380617018914066)),
 (350, np.float64(0.3380617018914066)),
 (398, np.float64(0.3380617018914066)),
 (455, np.float64(0.3380617018914066)),
 (456, np.float64(0.3380617018914066)),
 (711, np.float64(0.3380617018914066)),
 (748, np.float64(0.3380617018914066)),
 (755, np.float64(0.3380617018914066)),
 (1119, np.float64(0.3380617018914066)),
 (1140, np.float64(0.3380617018914066)),
 (1153, np.float64(0.3380617018914066)),
 (37, np.float64(0.3162277660168379)),
 (148, np.float64(0.3162277660168379)),
 (211, np.float64(0.3162277660168379)),
 (217, np.float64(0.3162277660168379)),
 (279, np.float64(0.3162277660168379)),
 (280, np.float64(0.3162277660168379)),
 (283, np.float64(0.3162277660168379)),
 (356, np.float64(0.3162277660168379)),
 (359, np.float64(0.3162277660168379)),
 (364, np.float64(0.3162277660168379)),
 (387, np.float64(0.3162277660168379)),
 (423, np.float64(0.3162277660168379)),
 (428, np.float64(0.3162277660168379)),
 (460, np.float64(0.3162277660168379)),
 (466, np.float64(0.3162277660168379)),
 (478, np.float64(0.3162277660168379)),
 (487, np.float64(0.3162277660168379)),
 (518, np.float64(0.3162277660168379)),
 (563, np.float64(0.3162277660168379)),
 (589, np.float64(0.3162277660168379)),
 (592, np.float64(0.3162277660168379)),
 (593, np.float64(0.3162277660168379)),
 (610, np.float64(0.3162277660168379)),
 (617, np.float64(0.3162277660168379)),
 (672, np.float64(0.3162277660168379)),
 (674, np.float64(0.3162277660168379)),
 (676, np.float64(0.3162277660168379)),
 (678, np.float64(0.3162277660168379)),
 (686, np.float64(0.3162277660168379)),
 (688, np.float64(0.3162277660168379)),
 (705, np.float64(0.3162277660168379)),
 (735, np.float64(0.3162277660168379)),
 (797, np.float64(0.3162277660168379)),
 (873, np.float64(0.3162277660168379)),
 (882, np.float64(0.3162277660168379)),
 (905, np.float64(0.3162277660168379)),
 (911, np.float64(0.3162277660168379)),
 (916, np.float64(0.3162277660168379)),
 (929, np.float64(0.3162277660168379)),
 (948, np.float64(0.3162277660168379)),
 (951, np.float64(0.3162277660168379)),
 (972, np.float64(0.3162277660168379)),
 (989, np.float64(0.3162277660168379)),
 (1012, np.float64(0.3162277660168379)),
 (1015, np.float64(0.3162277660168379)),
 (1016, np.float64(0.3162277660168379)),
 (1029, np.float64(0.3162277660168379)),
 (1032, np.float64(0.3162277660168379)),
 (1042, np.float64(0.3162277660168379)),
 (1043, np.float64(0.3162277660168379)),
 (1045, np.float64(0.3162277660168379)),
 (1048, np.float64(0.3162277660168379)),
 (1065, np.float64(0.3162277660168379)),
 (1092, np.float64(0.3162277660168379)),
 (1105, np.float64(0.3162277660168379)),
 (1106, np.float64(0.3162277660168379)),
 (1136, np.float64(0.3162277660168379)),
 (1171, np.float64(0.3162277660168379)),
 (1176, np.float64(0.3162277660168379)),
 (1177, np.float64(0.3162277660168379)),
 (26, np.float64(0.2981423969999719)),
 (175, np.float64(0.2981423969999719)),
 (209, np.float64(0.2981423969999719)),
 (236, np.float64(0.2981423969999719)),
 (326, np.float64(0.2981423969999719)),
 (338, np.float64(0.2981423969999719)),
 (366, np.float64(0.2981423969999719)),
 (643, np.float64(0.2981423969999719)),
 (903, np.float64(0.2981423969999719)),
 (1098, np.float64(0.2981423969999719)),
 (1164, np.float64(0.2981423969999719)),
 (616, np.float64(0.282842712474619)),
 (396, np.float64(0.26967994498529685)),
 (1154, np.float64(0.26967994498529685)),
 (116, np.float64(0.25819888974716115)),
 (154, np.float64(0.25819888974716115)),
 (161, np.float64(0.25819888974716115)),
 (170, np.float64(0.25819888974716115)),
 (188, np.float64(0.25819888974716115)),
 (253, np.float64(0.25819888974716115)),
 (275, np.float64(0.25819888974716115)),
 (276, np.float64(0.25819888974716115)),
 (282, np.float64(0.25819888974716115)),
 (303, np.float64(0.25819888974716115)),
 (308, np.float64(0.25819888974716115)),
 (309, np.float64(0.25819888974716115)),
 (316, np.float64(0.25819888974716115)),
 (335, np.float64(0.25819888974716115)),
 (336, np.float64(0.25819888974716115)),
 (337, np.float64(0.25819888974716115)),
 (373, np.float64(0.25819888974716115)),
 (380, np.float64(0.25819888974716115)),
 (395, np.float64(0.25819888974716115)),
 (406, np.float64(0.25819888974716115)),
 (410, np.float64(0.25819888974716115)),
 (412, np.float64(0.25819888974716115)),
 (414, np.float64(0.25819888974716115)),
 (415, np.float64(0.25819888974716115)),
 (424, np.float64(0.25819888974716115)),
 (434, np.float64(0.25819888974716115)),
 (438, np.float64(0.25819888974716115)),
 (449, np.float64(0.25819888974716115)),
 (452, np.float64(0.25819888974716115)),
 (464, np.float64(0.25819888974716115)),
 (469, np.float64(0.25819888974716115)),
 (475, np.float64(0.25819888974716115)),
 (481, np.float64(0.25819888974716115)),
 (484, np.float64(0.25819888974716115)),
 (485, np.float64(0.25819888974716115)),
 (494, np.float64(0.25819888974716115)),
 (545, np.float64(0.25819888974716115)),
 (548, np.float64(0.25819888974716115)),
 (558, np.float64(0.25819888974716115)),
 (580, np.float64(0.25819888974716115)),
 (595, np.float64(0.25819888974716115)),
 (604, np.float64(0.25819888974716115)),
 (608, np.float64(0.25819888974716115)),
 (629, np.float64(0.25819888974716115)),
 (636, np.float64(0.25819888974716115)),
 (646, np.float64(0.25819888974716115)),
 (651, np.float64(0.25819888974716115)),
 (660, np.float64(0.25819888974716115)),
 (663, np.float64(0.25819888974716115)),
 (667, np.float64(0.25819888974716115)),
 (668, np.float64(0.25819888974716115)),
 (734, np.float64(0.25819888974716115)),
 (750, np.float64(0.25819888974716115)),
 (781, np.float64(0.25819888974716115)),
 (782, np.float64(0.25819888974716115)),
 (816, np.float64(0.25819888974716115)),
 (817, np.float64(0.25819888974716115)),
 (818, np.float64(0.25819888974716115)),
 (836, np.float64(0.25819888974716115)),
 (838, np.float64(0.25819888974716115)),
 (843, np.float64(0.25819888974716115)),
 (859, np.float64(0.25819888974716115)),
 (878, np.float64(0.25819888974716115)),
 (881, np.float64(0.25819888974716115)),
 (883, np.float64(0.25819888974716115)),
 (912, np.float64(0.25819888974716115)),
 (920, np.float64(0.25819888974716115)),
 (931, np.float64(0.25819888974716115)),
 (935, np.float64(0.25819888974716115)),
 (957, np.float64(0.25819888974716115)),
 (968, np.float64(0.25819888974716115)),
 (971, np.float64(0.25819888974716115)),
 (973, np.float64(0.25819888974716115)),
 (976, np.float64(0.25819888974716115)),
 (981, np.float64(0.25819888974716115)),
 (986, np.float64(0.25819888974716115)),
 (992, np.float64(0.25819888974716115)),
 (1002, np.float64(0.25819888974716115)),
 (1007, np.float64(0.25819888974716115)),
 (1019, np.float64(0.25819888974716115)),
 (1030, np.float64(0.25819888974716115)),
 (1068, np.float64(0.25819888974716115)),
 (1079, np.float64(0.25819888974716115)),
 (1081, np.float64(0.25819888974716115)),
 (1088, np.float64(0.25819888974716115)),
 (1091, np.float64(0.25819888974716115)),
 (1096, np.float64(0.25819888974716115)),
 (1101, np.float64(0.25819888974716115)),
 (1112, np.float64(0.25819888974716115)),
 (1118, np.float64(0.25819888974716115)),
 (1142, np.float64(0.25819888974716115)),
 (1161, np.float64(0.25819888974716115)),
 (1172, np.float64(0.25819888974716115)),
 (1179, np.float64(0.25819888974716115)),
 (3518, np.float64(0.25819888974716115)),
 (254, np.float64(0.23904572186687872)),
 (2, np.float64(0.22360679774997896)),
 (19, np.float64(0.22360679774997896)),
 (50, np.float64(0.22360679774997896)),
 (53, np.float64(0.22360679774997896)),
 (58, np.float64(0.22360679774997896)),
 (67, np.float64(0.22360679774997896)),
 (74, np.float64(0.22360679774997896)),
 (84, np.float64(0.22360679774997896)),
 (86, np.float64(0.22360679774997896)),
 (97, np.float64(0.22360679774997896)),
 (99, np.float64(0.22360679774997896)),
 (106, np.float64(0.22360679774997896)),
 (112, np.float64(0.22360679774997896)),
 (119, np.float64(0.22360679774997896)),
 (134, np.float64(0.22360679774997896)),
 (140, np.float64(0.22360679774997896)),
 (159, np.float64(0.22360679774997896)),
 (160, np.float64(0.22360679774997896)),
 (178, np.float64(0.22360679774997896)),
 (179, np.float64(0.22360679774997896)),
 (185, np.float64(0.22360679774997896)),
 (197, np.float64(0.22360679774997896)),
 (213, np.float64(0.22360679774997896)),
 (224, np.float64(0.22360679774997896)),
 (225, np.float64(0.22360679774997896)),
 (234, np.float64(0.22360679774997896)),
 (237, np.float64(0.22360679774997896)),
 (242, np.float64(0.22360679774997896)),
 (245, np.float64(0.22360679774997896)),
 (263, np.float64(0.22360679774997896)),
 (272, np.float64(0.22360679774997896)),
 (273, np.float64(0.22360679774997896)),
 (277, np.float64(0.22360679774997896)),
 (287, np.float64(0.22360679774997896)),
 (289, np.float64(0.22360679774997896)),
 (301, np.float64(0.22360679774997896)),
 (307, np.float64(0.22360679774997896)),
 (340, np.float64(0.22360679774997896)),
 (355, np.float64(0.22360679774997896)),
 (357, np.float64(0.22360679774997896)),
 (363, np.float64(0.22360679774997896)),
 (383, np.float64(0.22360679774997896)),
 (385, np.float64(0.22360679774997896)),
 (391, np.float64(0.22360679774997896)),
 (408, np.float64(0.22360679774997896)),
 (421, np.float64(0.22360679774997896)),
 (422, np.float64(0.22360679774997896)),
 (427, np.float64(0.22360679774997896)),
 (437, np.float64(0.22360679774997896)),
 (445, np.float64(0.22360679774997896)),
 (457, np.float64(0.22360679774997896)),
 (468, np.float64(0.22360679774997896)),
 (477, np.float64(0.22360679774997896)),
 (479, np.float64(0.22360679774997896)),
 (504, np.float64(0.22360679774997896)),
 (506, np.float64(0.22360679774997896)),
 (514, np.float64(0.22360679774997896)),
 (516, np.float64(0.22360679774997896)),
 (519, np.float64(0.22360679774997896)),
 (520, np.float64(0.22360679774997896)),
 (523, np.float64(0.22360679774997896)),
 (524, np.float64(0.22360679774997896)),
 (534, np.float64(0.22360679774997896)),
 (536, np.float64(0.22360679774997896)),
 (538, np.float64(0.22360679774997896)),
 (544, np.float64(0.22360679774997896)),
 (547, np.float64(0.22360679774997896)),
 (574, np.float64(0.22360679774997896)),
 (577, np.float64(0.22360679774997896)),
 (581, np.float64(0.22360679774997896)),
 (585, np.float64(0.22360679774997896)),
 (600, np.float64(0.22360679774997896)),
 (606, np.float64(0.22360679774997896)),
 (609, np.float64(0.22360679774997896)),
 (611, np.float64(0.22360679774997896)),
 (613, np.float64(0.22360679774997896)),
 (615, np.float64(0.22360679774997896)),
 (618, np.float64(0.22360679774997896)),
 (623, np.float64(0.22360679774997896)),
 (635, np.float64(0.22360679774997896)),
 (640, np.float64(0.22360679774997896)),
 (641, np.float64(0.22360679774997896)),
 (650, np.float64(0.22360679774997896)),
 (662, np.float64(0.22360679774997896)),
 (680, np.float64(0.22360679774997896)),
 (682, np.float64(0.22360679774997896)),
 (683, np.float64(0.22360679774997896)),
 (691, np.float64(0.22360679774997896)),
 (708, np.float64(0.22360679774997896)),
 (709, np.float64(0.22360679774997896)),
 (710, np.float64(0.22360679774997896)),
 (714, np.float64(0.22360679774997896)),
 (716, np.float64(0.22360679774997896)),
 (717, np.float64(0.22360679774997896)),
 (719, np.float64(0.22360679774997896)),
 (727, np.float64(0.22360679774997896)),
 (739, np.float64(0.22360679774997896)),
 (743, np.float64(0.22360679774997896)),
 (752, np.float64(0.22360679774997896)),
 (763, np.float64(0.22360679774997896)),
 (765, np.float64(0.22360679774997896)),
 (771, np.float64(0.22360679774997896)),
 (775, np.float64(0.22360679774997896)),
 (778, np.float64(0.22360679774997896)),
 (787, np.float64(0.22360679774997896)),
 (806, np.float64(0.22360679774997896)),
 (808, np.float64(0.22360679774997896)),
 (809, np.float64(0.22360679774997896)),
 (810, np.float64(0.22360679774997896)),
 (813, np.float64(0.22360679774997896)),
 (819, np.float64(0.22360679774997896)),
 (820, np.float64(0.22360679774997896)),
 (824, np.float64(0.22360679774997896)),
 (829, np.float64(0.22360679774997896)),
 (839, np.float64(0.22360679774997896)),
 (840, np.float64(0.22360679774997896)),
 (857, np.float64(0.22360679774997896)),
 (858, np.float64(0.22360679774997896)),
 (860, np.float64(0.22360679774997896)),
 (871, np.float64(0.22360679774997896)),
 (889, np.float64(0.22360679774997896)),
 (901, np.float64(0.22360679774997896)),
 (913, np.float64(0.22360679774997896)),
 (918, np.float64(0.22360679774997896)),
 (921, np.float64(0.22360679774997896)),
 (923, np.float64(0.22360679774997896)),
 (925, np.float64(0.22360679774997896)),
 (928, np.float64(0.22360679774997896)),
 (930, np.float64(0.22360679774997896)),
 (933, np.float64(0.22360679774997896)),
 (940, np.float64(0.22360679774997896)),
 (944, np.float64(0.22360679774997896)),
 (946, np.float64(0.22360679774997896)),
 (956, np.float64(0.22360679774997896)),
 (964, np.float64(0.22360679774997896)),
 (969, np.float64(0.22360679774997896)),
 (970, np.float64(0.22360679774997896)),
 (974, np.float64(0.22360679774997896)),
 (975, np.float64(0.22360679774997896)),
 (978, np.float64(0.22360679774997896)),
 (985, np.float64(0.22360679774997896)),
 (998, np.float64(0.22360679774997896)),
 (999, np.float64(0.22360679774997896)),
 (1004, np.float64(0.22360679774997896)),
 (1006, np.float64(0.22360679774997896)),
 (1011, np.float64(0.22360679774997896)),
 (1017, np.float64(0.22360679774997896)),
 (1018, np.float64(0.22360679774997896)),
 (1022, np.float64(0.22360679774997896)),
 (1023, np.float64(0.22360679774997896)),
 (1026, np.float64(0.22360679774997896)),
 (1049, np.float64(0.22360679774997896)),
 (1053, np.float64(0.22360679774997896)),
 (1056, np.float64(0.22360679774997896)),
 (1060, np.float64(0.22360679774997896)),
 (1071, np.float64(0.22360679774997896)),
 (1073, np.float64(0.22360679774997896)),
 (1075, np.float64(0.22360679774997896)),
 (1078, np.float64(0.22360679774997896)),
 (1082, np.float64(0.22360679774997896)),
 (1083, np.float64(0.22360679774997896)),
 (1094, np.float64(0.22360679774997896)),
 (1122, np.float64(0.22360679774997896)),
 (1145, np.float64(0.22360679774997896)),
 (1147, np.float64(0.22360679774997896)),
 (1151, np.float64(0.22360679774997896)),
 (1152, np.float64(0.22360679774997896)),
 (1155, np.float64(0.22360679774997896)),
 (1163, np.float64(0.22360679774997896)),
 (1168, np.float64(0.22360679774997896)),
 (1185, np.float64(0.22360679774997896)),
 (3468, np.float64(0.22360679774997896)),
 (3651, np.float64(0.22360679774997896)),
 (4, np.float64(0.19999999999999998)),
 (11, np.float64(0.19999999999999998)),
 (18, np.float64(0.19999999999999998)),
 (34, np.float64(0.19999999999999998)),
 (56, np.float64(0.19999999999999998)),
 (66, np.float64(0.19999999999999998)),
 (68, np.float64(0.19999999999999998)),
 (72, np.float64(0.19999999999999998)),
 (77, np.float64(0.19999999999999998)),
 (78, np.float64(0.19999999999999998)),
 (82, np.float64(0.19999999999999998)),
 (88, np.float64(0.19999999999999998)),
 (91, np.float64(0.19999999999999998)),
 (95, np.float64(0.19999999999999998)),
 (96, np.float64(0.19999999999999998)),
 (101, np.float64(0.19999999999999998)),
 (102, np.float64(0.19999999999999998)),
 (103, np.float64(0.19999999999999998)),
 (126, np.float64(0.19999999999999998)),
 (129, np.float64(0.19999999999999998)),
 (130, np.float64(0.19999999999999998)),
 (131, np.float64(0.19999999999999998)),
 (132, np.float64(0.19999999999999998)),
 (133, np.float64(0.19999999999999998)),
 (141, np.float64(0.19999999999999998)),
 (142, np.float64(0.19999999999999998)),
 (163, np.float64(0.19999999999999998)),
 (166, np.float64(0.19999999999999998)),
 (167, np.float64(0.19999999999999998)),
 (168, np.float64(0.19999999999999998)),
 (177, np.float64(0.19999999999999998)),
 (183, np.float64(0.19999999999999998)),
 (189, np.float64(0.19999999999999998)),
 (191, np.float64(0.19999999999999998)),
 (194, np.float64(0.19999999999999998)),
 (201, np.float64(0.19999999999999998)),
 (207, np.float64(0.19999999999999998)),
 (212, np.float64(0.19999999999999998)),
 (214, np.float64(0.19999999999999998)),
 (216, np.float64(0.19999999999999998)),
 (218, np.float64(0.19999999999999998)),
 (219, np.float64(0.19999999999999998)),
 (232, np.float64(0.19999999999999998)),
 (247, np.float64(0.19999999999999998)),
 (252, np.float64(0.19999999999999998)),
 (255, np.float64(0.19999999999999998)),
 (256, np.float64(0.19999999999999998)),
 (257, np.float64(0.19999999999999998)),
 (265, np.float64(0.19999999999999998)),
 (268, np.float64(0.19999999999999998)),
 (269, np.float64(0.19999999999999998)),
 (271, np.float64(0.19999999999999998)),
 (284, np.float64(0.19999999999999998)),
 (290, np.float64(0.19999999999999998)),
 (299, np.float64(0.19999999999999998)),
 (300, np.float64(0.19999999999999998)),
 (302, np.float64(0.19999999999999998)),
 (304, np.float64(0.19999999999999998)),
 (310, np.float64(0.19999999999999998)),
 (312, np.float64(0.19999999999999998)),
 (315, np.float64(0.19999999999999998)),
 (318, np.float64(0.19999999999999998)),
 (321, np.float64(0.19999999999999998)),
 (322, np.float64(0.19999999999999998)),
 (323, np.float64(0.19999999999999998)),
 (327, np.float64(0.19999999999999998)),
 (328, np.float64(0.19999999999999998)),
 (330, np.float64(0.19999999999999998)),
 (331, np.float64(0.19999999999999998)),
 (332, np.float64(0.19999999999999998)),
 (333, np.float64(0.19999999999999998)),
 (334, np.float64(0.19999999999999998)),
 (346, np.float64(0.19999999999999998)),
 (348, np.float64(0.19999999999999998)),
 (362, np.float64(0.19999999999999998)),
 (371, np.float64(0.19999999999999998)),
 (374, np.float64(0.19999999999999998)),
 (376, np.float64(0.19999999999999998)),
 (377, np.float64(0.19999999999999998)),
 (382, np.float64(0.19999999999999998)),
 (392, np.float64(0.19999999999999998)),
 (401, np.float64(0.19999999999999998)),
 (405, np.float64(0.19999999999999998)),
 (413, np.float64(0.19999999999999998)),
 (416, np.float64(0.19999999999999998)),

In [178]:
def content_recomm(course):
    course_index = data[data['course_title'] == course].index[0]  #to get the index of the course
    sim = similarity[course_index]  #to get the similarity scores for the course
    course_list = sorted(enumerate(sim), reverse=True, key=lambda x: x[1])[1:6]  #to sort the similarity scores in descending order
    for i in course_list:
        print(data.iloc[i[0]]['course_title'])  #to get the course title for each course in the list

In [180]:
content_recomm('Ultimate Investment Banking Course')  #to get the recommended courses for the given course

Investment Banking Recruitment Series
Complete Investment Banking Course 2017
Financial Accounting  Ultimate Beginner Course
Managerial Accounting  Ultimate Beginner Course
Investment Banking Land Job Wall Street